import { Statement } from './types';

export const statements: Statement[] = [
  {
    id: 1,
    dimension: 'External Risk & Demand Stability',
    question: 'Our external demand behavior is best described as:',
    answerType: 'dropdown',
    dropdownOptions: [
      { label: 'Highly predictable', value: 5 },
      { label: 'Mostly predictable', value: 4 },
      { label: 'Mixed', value: 3 },
      { label: 'Mostly unpredictable', value: 2 },
      { label: 'Completely unpredictable', value: 1 },
    ],
    interpretation: 'Lower = volatility unmanaged; Higher = volatility understood',
  },
  {
    id: 2,
    dimension: 'Decision Ownership & Speed',
    question: 'We clearly know who makes the final decision.',
    answerType: 'yes-no',
    interpretation: 'Low = confusion; High = clarity',
  },
  {
    id: 3,
    dimension: 'End-to-End Process Flow',
    question: 'We all have a shared understanding of how an order moves from start to finish.',
    answerType: 'scale',
    interpretation: 'Low = silo view; High = system understanding',
  },
  {
    id: 4,
    dimension: 'Process Clarity & Ownership',
    question: 'We clearly know what triggers each key process.',
    answerType: 'scale',
    interpretation: 'Low = unclear triggers; High = clear initiation',
  },
  {
    id: 5,
    dimension: 'Strategic Focus & Capacity',
    question: 'Our current procurement and supply chain setup can realistically support our growth plans.',
    answerType: 'scale',
    interpretation: 'Low = overextension; High = feasible ambition',
  },
  {
    id: 6,
    dimension: 'External Risk & Demand Stability',
    question: 'When external risks increase, we actually adjust our plans instead of just talking about them.',
    answerType: 'yes-no',
    interpretation: 'No = talk only; Yes = structural impact',
  },
  {
    id: 7,
    dimension: 'Decision Ownership & Speed',
    question: 'Responsibility for decision-making is clear for each key process.',
    answerType: 'yes-no',
    interpretation: 'No = unclear authority',
  },
  {
    id: 8,
    dimension: 'End-to-End Process Flow',
    question: 'Changes in one area rarely create problems elsewhere.',
    answerType: 'scale',
    interpretation: 'Low = system friction',
  },
  {
    id: 9,
    dimension: 'Process Clarity & Ownership',
    question: 'For each key process, we clearly know who provides the input and who receives the output.',
    answerType: 'scale',
    interpretation: 'No = unclear ownership; Yes = clear boundaries',
  },
  {
    id: 10,
    dimension: 'Strategic Focus & Capacity',
    question: 'We are clear about our priorities and consciously say no to non-essential work.',
    answerType: 'scale',
    interpretation: 'No = everything is priority; Yes = focus',
  },
  {
    id: 11,
    dimension: 'External Risk & Demand Stability',
    question: 'We are rarely surprised by sudden changes in customer demand.',
    answerType: 'dropdown',
    dropdownOptions: [
      { label: 'Very rarely surprised', value: 5 },
      { label: 'Rarely surprised', value: 4 },
      { label: 'Sometimes surprised', value: 3 },
      { label: 'Often surprised', value: 2 },
      { label: 'Very often surprised', value: 1 },
    ],
    interpretation: 'Low = constant surprises; High = demand behavior understood',
  },
  {
    id: 12,
    dimension: 'Decision Ownership & Speed',
    question: 'Our decision speed in critical situations is best described as:',
    answerType: 'dropdown',
    dropdownOptions: [
      { label: 'Very fast', value: 5 },
      { label: 'Fast enough', value: 4 },
      { label: 'Acceptable', value: 3 },
      { label: 'Slow', value: 2 },
      { label: 'Very slow', value: 1 },
    ],
    interpretation: 'Lower = execution bottleneck',
  },
  {
    id: 13,
    dimension: 'End-to-End Process Flow',
    question: 'Lead times are consistently considered in planning decisions.',
    answerType: 'scale',
    interpretation: 'Low = surprises',
  },
  {
    id: 14,
    dimension: 'Process Clarity & Ownership',
    question: 'The quality of handoffs between our processes is:',
    answerType: 'dropdown',
    dropdownOptions: [
      { label: 'Very clear and reliable', value: 5 },
      { label: 'Mostly clear, minor issues', value: 4 },
      { label: 'Inconsistent', value: 3 },
      { label: 'Often unclear', value: 2 },
      { label: 'Very unclear and error-prone', value: 1 },
    ],
    interpretation: 'Lower = flow disruption',
  },
  {
    id: 15,
    dimension: 'Strategic Focus & Capacity',
    question: 'Our current operational load is best described as:',
    answerType: 'dropdown',
    dropdownOptions: [
      { label: 'Well balanced', value: 5 },
      { label: 'Manageable with some pressure', value: 4 },
      { label: 'Often stretched', value: 3 },
      { label: 'Constantly overloaded', value: 2 },
      { label: 'Overwhelming', value: 1 },
    ],
    interpretation: 'Lower = unsustainable execution',
  },
];

// Get unique dimensions/categories
export const dimensions = Array.from(new Set(statements.map(s => s.dimension)));
